# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3aec913ed32f46ea609db265a7ea77ce0c81194a223bd27388522cae3175f24eeacc1aaad20857a86b2926e3093d6abc8c6159949690221f69ce978218aac1ce

test:
  secret_key_base: affca6f49b720522ed5e93b37ef6b0dc7b3fcbc4ea0f36b32ed4c0a887c2d4121228baf28e76937869a79fc15d1231d7cc24807fd6bf398348d9f1b0a68a9a42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
